#!/bin/bash
# update homebrew and casks
set -euo pipefail
export HOMEBREW_NO_ENV_HINTS=1
export HOMEBREW_INSTALL_CLEANUP=1
source uptitle

title homebrew
brew update --merge --auto-update
brew upgrade --greedy
if ! which node; then
    # Fix node unlinking all the time.
    brew link --overwrite node
fi
brew cleanup
