#!/usr/bin/env bash
# update homebrew formulae and casks
set -euo pipefail
export HOMEBREW_NO_ENV_HINTS=1
# shellcheck source=uptitle
source "$(dirname "$0")/uptitle"

title homebrew
brew upgrade --yes
if ! command -v node >/dev/null; then
  # Fix node unlinking all the time.
  brew link --overwrite node
fi
brew cleanup
