#!/bin/sh
set -eux
if [ "${1:-}" = '-l' ]; then
    target_cmd="ln -sf"
else
    target_cmd="cp"
fi


# basics
brew install python2 python3 npm ruby rbenv perl cpanm

# python
pip2 install pip-review
mv /usr/local/bin/pip-review /usr/local/bin/pip-review2
pip3 install pip-review

# node
# n/a

# ruby
# n/a

# perl
cpanm App::cpanoutdated
ln -sf /usr/local/Cellar/perl/*/bin/cpan-outdated /usr/local/bin/

# this repo's custom scripts
$target_cmd "$PWD"/brewup "$PWD"/upall "$PWD"/gemup "$PWD"/perlup /usr/local/bin/
