#!/usr/bin/env bash
# install the update scripts
set -eux
if [ "${1:-}" = '-l' ]; then
  target_cmd="ln -sf"
else
  target_cmd="cp"
fi

# the scripts this repo installs
SCRIPTS=(uptitle brewup upall gemup perlup nodeup rustup pipup luaup)

# basics
brew install rust python3 npm ruby rbenv luarocks perl cpanm

# rust
cargo install cargo-update || true

# python
VENV_DIR="$HOME"/.venv
python3 -m venv --upgrade --upgrade-deps "$VENV_DIR"
"$VENV_DIR"/bin/pip install -U pip-review

# node
# n/a

# ruby
# n/a

# perl
cpanm App::cpanoutdated

# this repo's custom scripts
DEST_DIR=/usr/local/bin
for script in "${SCRIPTS[@]}"; do
  rm -f "$DEST_DIR/$script"
  $target_cmd "$PWD/$script" "$DEST_DIR/$script"
done
