#!/bin/sh
# install the update scripts
set -eux
if [ "${1:-}" = '-l' ]; then
    target_cmd="ln -sf"
else
    target_cmd="cp"
fi

# basics
brew install rust python3 npm ruby rbenv luarocks perl cpanm

# rust
cargo install cargo-update || true

# python
python3 -m venv "$HOME"/.venv
pip3 install pip-review

# node
# n/a

# ruby
# n/a

# perl
cpanm App::cpanoutdated
# shellcheck disable=SC2086
BREW_PREFIX=$(brew --prefix)
ln -sf "$BREW_PREFIX"/Cellar/perl/*/bin/cpan-outdated /usr/local/bin/

# this repo's custom scripts
"$target_cmd" "$PWD"/uptitle "$PWD"/brewup "$PWD"/upall "$PWD"/gemup "$PWD"/perlup "$PWD"/nodeup "$PWD"/rustup "$PWD"/pipup "$PWD"/luaup /usr/local/bin/
