#!/bin/bash
# update all perl packages
set -uo pipefail

source uptitle

title perl
# Lazy auto install of cpanm-outdated, as it is occasionally uninstalled by
# something
cpanm App::cpanoutdated | grep -v "App::cpanoutdated is up to date." || true
ln -sf /usr/local/Cellar/perl/*/bin/cpan-outdated /usr/local/bin/

# Only update if there are things to update.
PACKAGES=$(cpan-outdated)
if [ -n "$PACKAGES" ]; then
  set -x
  # shellcheck disable=SC2086
  cpanm $PACKAGES
else
  echo Perl is up to date.
fi
