#!/bin/sh
printf "Finding outdated packages..."
EXCLUDE='Could\ not\ find\|You\ are\|You\ should\|Some insecure\|The\ directory'
LIST=$(pip list -lo | grep -v "$EXCLUDE" | cut -d ' ' -f 1 | tr '\n' ' ')

# Not sure if still neccissary
#for item in $SOME_LIST; do
#    if [ "$item" != "Some" ]; then
#        LIST=$LIST" "$i
#    fi
#done;

if [ -n "$LIST" ]; then
    echo
    cmd="pip install -U $LIST"
    echo "$cmd"
    $cmd
else
    echo everything is up to date!
fi
echo done.
