#!/bin/sh
PIPVERSION=`pip -V | cut -d ' ' -f 2`
printf "Finding outdated packages..."
if [  "$PIPVERSION" \< "1.3" ]; then
  LIST=`pip freeze --local | egrep -v '^(\-e|[[:space:]]*#)' | cut -d = -f 1  | tr '\n' ' '`
else
  SOME_LIST=`pip list -lo --allow-all-external | grep -v '^Could\ not\|^You\ are\ installing|^Some' | cut -d ' ' -f 1 | tr '\n' ' '`
  #TODO Fix Regex Some thing
  for i in $SOME_LIST; do
      if [[ "$i" != "Some" ]]; then
        LIST=$LIST" "$i
      fi
   done;
fi
if [ -n "$LIST" ]; then
    echo upgrading: $LIST
    pip install -U $LIST
else
    echo everything is up to date!
fi
echo done.
