#!/bin/sh
printf "Finding outdated packages..."
EXCLUDE='Could\ not\ find\|You\ are\|You\ should\|^Some\|Some insecure\|The\ directory'
LIST=$(pip list --local --outdated | grep -v "$EXCLUDE" | cut -d ' ' -f 1)

if [ -n "$LIST" ]; then
    echo
    cmd="pip install -U $LIST"
    echo "$cmd"
    $cmd
else
    echo everything is up to date!
fi
echo done.
