#!/usr/bin/env bash
# update rust cargo
set -euo pipefail

# shellcheck source=uptitle
source "$(dirname "$0")/uptitle"

title rust
# Use homebrew's libcurl instead of the system one when it is installed.
DYLD_INSERT_LIBRARIES="$(brew --prefix)/opt/curl/lib/libcurl.dylib"
if [ -f "$DYLD_INSERT_LIBRARIES" ]; then
  export DYLD_INSERT_LIBRARIES
fi
cargo install-update -a
