#!/bin/sh
set -eu

BOLD=$(tput bold)
NORMAL=$(tput sgr0)

title() {
  echo "${BOLD}Updating $*:${NORMAL}"
}

title "homebrew"
brewup
title "python"
pip-review --auto
title "node"
npm -g update
title "ruby"
gemup
title "perl"
perlup
