#!/bin/sh
# run all the update scripts
set -eu

BOLD=$(tput bold)
NORMAL=$(tput sgr0)

title() {
  echo "${BOLD}Updating $*:${NORMAL}"
}

title "homebrew"
brewup
title "rust"
cargo install-update -a
title "python3"
pip-review --auto
title "python2"
pip-review2 --auto
title "node"
npm -g update
title "ruby"
gemup
title "perl"
perlup
